// The MIT License (MIT)
// 
// Copyright (c) 2015, Axel Habermaier
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

namespace PointWars.UserInterface.Controls
{
	using System.Collections.Generic;
	using Rendering;
	using Utilities;

	/// <summary>
	///   A base class for all panel elements that position and arrange child UI elements.
	/// </summary>
	public abstract class Panel : UIElement, IScrollAware
	{
		/// <summary>
		///   A lookup table in which the child elements are sorted by z index.
		/// </summary>
		private readonly List<int> _zLookup = new List<int>(16);

		/// <summary>
		///   A value indicating whether the child UI elements must be sorted by z-index again before drawing.
		/// </summary>
		private bool _zOrderDirty;

		/// <summary>
		///   Initializes a new instance.
		/// </summary>
		protected Panel()
		{
			Children = new UIElementCollection(this);
		}

		/// <summary>
		///   Gets or sets the collection of layouted children.
		/// </summary>
		public UIElementCollection Children { get; }

		/// <summary>
		///   Gets or sets a value indicating that the panel is a host for items generated by a control such as items control.
		/// </summary>
		public bool IsItemsHost { get; set; }

		/// <summary>
		///   Gets the number of children for this visual.
		/// </summary>
		protected internal override sealed int ChildrenCount => Children?.Count ?? 0;

		/// <summary>
		///   Gets or sets the scroll handler that handles this scrolling aware UI element.
		/// </summary>
		public IScrollHandler ScrollHandler { get; set; }

		/// <summary>
		///   Gets an enumerator that can be used to enumerate all children of the panel.
		/// </summary>
		protected override sealed Enumerator<UIElement> GetChildren()
		{
			if (Children == null)
				return Enumerator<UIElement>.Empty;

			return Children.GetEnumerator();
		}

		/// <summary>
		///   Adds the given UI element to the panel.
		/// </summary>
		/// <param name="element">The UI element that should be added.</param>
		public void Add(UIElement element)
		{
			Assert.ArgumentNotNull(element, nameof(element));
			Children.Add(element);
		}

		/// <summary>
		///   Removes the given UI element from the panel.
		/// </summary>
		/// <param name="element">The UI element that should be removed.</param>
		public bool Remove(UIElement element)
		{
			Assert.ArgumentNotNull(element, nameof(element));
			return Children.Remove(element);
		}

		/// <summary>
		///   Removes all child UI elements from the panel.
		/// </summary>
		public void Clear()
		{
			Children.Clear();
		}

		/// <summary>
		///   Sets the z-order dirty flag if a panel's child element's z-index property has changed.
		/// </summary>
		public void ZIndicesChanged()
		{
			_zOrderDirty = true;
		}

		/// <summary>
		///   Invoked when the visual children of the UI element have changed.
		/// </summary>
		protected internal override void OnChildrenChanged()
		{
			_zOrderDirty = true;
		}

		/// <summary>
		///   Gets the child at the specified index.
		/// </summary>
		/// <param name="index">The zero-based index of the child that should be returned.</param>
		protected internal override sealed UIElement GetChild(int index)
		{
			Assert.NotNull(Children);
			Assert.ArgumentInRange(index, Children, nameof(index));

			if (_zOrderDirty)
				SortByZIndex();

			return Children[_zLookup[index]];
		}

		/// <summary>
		///   Sorts the child UI elements by their z-indices. Insertion sort is used as typically the number of
		///   child UI elements is rather low and they are mostly sorted anyway.
		/// </summary>
		private void SortByZIndex()
		{
			_zLookup.Clear();
			for (var i = 0; i < Children.Count; ++i)
				_zLookup.Add(i);

			for (var i = 1; i < Children.Count; ++i)
			{
				var item = Children[i];
				var itemZIndex = item.ZIndex;

				// Shift down the items until we find the index where the current item should be inserted.
				var j = i;
				for (; j > 0 && itemZIndex < Children[_zLookup[j - 1]].ZIndex; --j)
					_zLookup[j] = _zLookup[j - 1];

				_zLookup[j] = i;
			}

			_zOrderDirty = false;
		}

		/// <summary>
		///   Draws the child UI elements of the current UI element using the given sprite batch.
		/// </summary>
		/// <param name="spriteBatch">The sprite batch that should be used to draw the UI element's children.</param>
		protected override void DrawChildren(SpriteBatch spriteBatch)
		{
			if (ScrollHandler != null)
			{
				// We draw the children on a higher layer to avoid draw ordering issues.
				++spriteBatch.Layer;

				// Only draw the children that are actually visible
				var area = ScrollHandler.ScrollArea;
				foreach (var child in Children)
				{
					var topIsInside = child.VisualOffset.Y <= area.Bottom;
					var bottomIsInside = child.VisualOffset.Y + child.ActualHeight >= area.Top;
					var leftIsInside = child.VisualOffset.X <= area.Right;
					var rightIsInside = child.VisualOffset.X + child.ActualWidth >= area.Left;

					if (topIsInside && bottomIsInside && leftIsInside && rightIsInside)
						child.Draw(spriteBatch);
				}

				--spriteBatch.Layer;
			}
			else
				base.DrawChildren(spriteBatch);
		}
	}
}